School.WebApp/Areas/Manger/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace School.WebApp.Areas.Manger.Controllers
{
    [Area("Manger")]
    [Authorize(Roles = "MangerRole")]
    public class SubjectsController : Controller
    {

        private readonly ApplicationDbContext _context;
        public string UserEmail;
        private readonly IHttpContextAccessor _HttpContextAccessor;
        public SubjectsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            UserEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;

        }

        // GET: Manger/Subjects
        public async Task<IActionResult> GetAll()
        {
            var model = new SubjectViewModel();
            model.SubjectList = _context.Subject.Where(d=>d.IsDelete != true).Include(s => s.Class).Include(s => s.Teacher).ToList();
            return View(model);
        }

         public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .Include(s => s.Class)
                .Include(s => s.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

         public IActionResult Create()
         {
            SubjectViewModel model = new SubjectViewModel()
            {
                ClassDrop = _context.Classes.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }),
                TeacherDrop = _context.Teacher.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.FullName
                }),

            };
  
            return View(model);
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Subject.CreatedAt = DateTime.Now;
                model.Subject.CreatedBy = UserEmail;
                model.Subject.IsDelete = false;


                _context.Add(model.Subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(GetAll));
            }
             return View(model);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var model = new SubjectViewModel();
            model.Subject = await _context.Subject.FindAsync(id);

            model.ClassDrop = _context.Classes.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            model.TeacherDrop = _context.Teacher.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.FullName
            });

            if (model.Subject == null)
            {
                return NotFound();
            }
            return View(model);
 
        }

           [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SubjectViewModel model)
        {
            if (id != model.Subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    model.Subject.UpdatedAt = DateTime.Now;
                    model.Subject.UpdatedBy = UserEmail; 

                    _context.Update(model.Subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(model.Subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(GetAll));
            }
             return View(model);
        }

         public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .Include(s => s.Class)
                .Include(s => s.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

         [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subject.FindAsync(id);
            subject.IsDelete = true;
            _context.Subject.Update(subject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(GetAll));
        }





        [HttpPost]
        public IActionResult ExporDataToFile()
        {
            var dictioneryexportType = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            var exportType = dictioneryexportType["Export"];
            var model = GetDataDetail();
            switch (exportType)
            {


                case "Pdf":
                    ExportToPdf(model);
                    break;


            }
            return null;
        } 
        private void ExportToPdf(DataTable model)
        {

            if (model.Rows.Count > 0)
            {
                string fontLoc = @"./ARIALUNI.ttf"; // make sure to have the correct path to the font file

                int pdfRowIndex = 1;
                string filename = "عرض المواد الدراسية  " + DateTime.Now.ToString("dd-MM-yyyy hh_mm_s_tt");
                string filepath = MyServer.MapPath("\\") + "" + filename + ".pdf";
                Document document = new Document(PageSize.A4, 5f, 5f, 10f, 10f);
                FileStream fs = new FileStream(filepath, FileMode.Create);
                PdfWriter writer = PdfWriter.GetInstance(document, fs);
                document.Open();

                Font font1 = FontFactory.GetFont(FontFactory.COURIER_BOLD, 13);
                Font font2 = FontFactory.GetFont(FontFactory.COURIER, 8);
                BaseFont bf = BaseFont.CreateFont(fontLoc, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                Font f = new Font(bf, 8);

                Font fHeader = new Font(bf, 11);


                float[] columnDefinitionSize = { 5f, 5f, 5f };
                PdfPTable table;
                PdfPCell cell;

                table = new PdfPTable(3)
                {
                    WidthPercentage = 100
                };

               
                table.RunDirection = PdfWriter.RUN_DIRECTION_RTL;

                table.AddCell(new Phrase("اسم المادة    ", fHeader));
                table.AddCell(new Phrase("للصف  ", fHeader));
                table.AddCell(new Phrase("مدرس المادة    ", fHeader));

      


                foreach (DataRow data in model.Rows)
                {
                    table.AddCell(new Phrase(data["Name"].ToString(), f));
                    table.AddCell(new Phrase(data["Class"].ToString(), f));
                    table.AddCell(new Phrase(data["Teacher"].ToString(), f));
               

 
                    pdfRowIndex++;
                }
                document.Add(table);
                document.Close();
                document.CloseDocument();
                document.Dispose();
                writer.Close();
                writer.Dispose();
                fs.Close();
                fs.Dispose();
                FileStream sourceFile = new FileStream(filepath, FileMode.Open);
                float fileSize = 0;
                fileSize = sourceFile.Length;
                byte[] getContent = new byte[Convert.ToInt32(Math.Truncate(fileSize))];
                sourceFile.Read(getContent, 0, Convert.ToInt32(sourceFile.Length));
                sourceFile.Close();
                Response.Clear();
                Response.Headers.Clear();
                Response.ContentType = "application/pdf";
                Response.Headers.Add("Content-Length", getContent.Length.ToString());
                Response.Headers.Add("Content-Disposition", "attachment; filename=" + filename + ".pdf;");
                Response.Body.WriteAsync(getContent);
                Response.Body.Flush();
            }
        }
        private DataTable GetDataDetail()
        {
            var ModelList = _context.Subject
            .Include(w => w.Class)
             .Include(w => w.Teacher) 
            .ToList();

            DataTable dtProduct = new DataTable(" عرض التقييمات الدراسية  ");
            dtProduct.Columns.AddRange(new DataColumn[] {
                 new DataColumn("Name"),
                new DataColumn("Class"),
                new DataColumn("Teacher") 


            });
            foreach (var model in ModelList)
            {
                dtProduct.Rows.Add(model.Name, model.Class.Name, model.Teacher.FullName 
                                   );
            }

            return dtProduct;
        }

School.WebApp/Areas/StudentUser/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApp.Areas.StudentUser.Controllers
{
    [Area("StudentUser")]
    [Authorize(Roles = "StudentRole")]

    public class SubjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public string StudentEmail;
        public int StudentUserId;
        private readonly IHttpContextAccessor _HttpContextAccessor;
       



        public SubjectsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _HttpContextAccessor = httpContextAccessor;
            StudentEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;
            StudentUserId = _context.Student.Where(d => d.EmailAddress == StudentEmail).Select(d => d.Id).FirstOrDefault();

        }
 
        public async Task<IActionResult> GetSubjects()
        {
            SubjectViewModel model = new SubjectViewModel(); 
            int classId = _context.Student.Where(d => d.Id == StudentUserId).Select(d => d.ClassId).FirstOrDefault();
            model.SubjectList = _context.Subject.Include(d=>d.Class).Include(s=>s.Teacher).Where(s => s.ClassId == classId).ToList();
            return View(model);
        }


        

        private bool SubjectExists(int id)
        {
            return _context.Subject.Any(e => e.Id == id);
        }
    }
}

School.WebApp/Areas/Manger/Views/Subjects/Create.cshtml
@model School.Data.ViewModels.SubjectViewModel

@{
    ViewData["Title"] = "إنشاء مادة ";
}


<link rel="stylesheet" href="~/assets/TFiles/css/CreateStyle.css" />
<link rel="stylesheet" href="~/css/CreateEditMediaQuery.css" />



<form class="kt-form" id="kt_form" asp-action="Create">
    <div class="col-md-12">
        <div class="footer-section">
            <div class="row" style="color: #fff; background-color: #8c9cd0; padding: 15px;">

                <div class="col-6 text-left">
                    <div>
                        <div class="save-click">
                            <input type="submit" value="حفظ" class="btn btn-primary" style="color: #fff; border-color: #8c9cd0; background-color: #8c9cd0; " />
                            <i class="fa-solid fa-check" style=" padding-right: 10px;"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 text-right">
                    <div class="back-click">
                        <div style="padding-top: 5px; color: #fff; font-size: 20px; font-family: 'Changa', sans-serif; ">
                            <span class="">
                                إضافة مادة دراسية
                            </span>
                            <i class="fa-solid fa-plus"></i>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container-fluid mt-5 mb-3">
        <div class="row  text-right">
            <div class="kt-content  kt-grid__item kt-grid__item--fluid col-12" id="kt_content">
                <div class="row">
                    <div class="col-lg-12">
                        <!--begin::Portlet-->
                        <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile" id="kt_page_portlet">

                            <div class="kt-portlet__body">

                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="row">
                                    <div class="col-xl-2"></div>
                                    <div class="col-xl-8">
                                        <div class="kt-section kt-section--first">
                                            <div class="kt-section__body">
                                                <h3 class="kt-section__title kt-section__title-lg " style="text-align: right;"> : البيانات الأساسية </h3>
                                                <div class="form-group row">
                                                    <div class="col-9">
                                                        <input asp-for="@Model.Subject.Name" class="form-control" />
                                                    </div>
                                                    <label class="col-3 col-form-label">اسم المادة </label>
                                                </div>
                                                <div class="form-group row">
                                                    <div class="col-9">
                                                        <select asp-for="@Model.Subject.ClassId" class="form-control" asp-items="Model.ClassDrop"></select>
                                                    </div>
                                                    <label class="col-3 col-form-label"> تحديد الصف </label>
                                                </div>

                                                <div class="form-group row">
                                                    <div class="col-9">
                                                        <select asp-for="@Model.Subject.TeacherId" class="form-control" asp-items="Model.TeacherDrop">
                                                            <option selected>-- الرجاء إختيار معلم المادة --</option>
                                                        </select>
                                                    </div>
                                                    <label class="col-3 col-form-label">  تحديد معلم المادة        </label>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="kt-separator kt-separator--border-dashed kt-separator--space-lg"></div>
                                        <div class="kt-section">
                                            <div class="kt-section__body">






                                            </div>
                                        </div>


                                    </div>
                                    <div class="col-xl-2"></div>
                                </div>

                            </div>
                        </div>

                        <!--end::Portlet-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.WebApp/Areas/Manger/Views/Subjects/Delete.cshtml
@model School.Data.Entities.Subject

@{
    ViewData["Title"] = "حذف طالب ";
}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

@*<link href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

<style>
    .modal-confirm {
        color: #636363;
        width: 400px;
        margin: 30px auto;
    }

        .modal-confirm .modal-content {
            padding: 20px;
            border-radius: 5px;
            border: none;
            text-align: center;
            font-size: 14px;
        }

        .modal-confirm .modal-header {
            border-bottom: none;
            position: relative;
        }

        .modal-confirm h4 {
            text-align: center;
            font-size: 26px;
            margin: 30px 0 -10px;
        }

        .modal-confirm .close {
            position: absolute;
            top: -5px;
            right: -2px;
        }

        .modal-confirm .modal-body {
            color: #999;
        }

        .modal-confirm .modal-footer {
            border: none;
            text-align: center;
            border-radius: 5px;
            font-size: 13px;
            padding: 10px 15px 25px;
        }

            .modal-confirm .modal-footer a {
                color: #999;
            }

        .modal-confirm .icon-box {
            width: 80px;
            height: 80px;
            margin: 0 auto;
            border-radius: 50%;
            z-index: 9;
            text-align: center;
            border: 3px solid #f15e5e;
        }

            .modal-confirm .icon-box i {
                color: #f15e5e;
                font-size: 46px;
                display: inline-block;
                margin-top: 13px;
            }

        .modal-confirm .btn {
            color: #fff;
            border-radius: 4px;
            background: #60c7c1;
            text-decoration: none;
            transition: all 0.4s;
            line-height: normal;
            min-width: 120px;
            border: none;
            min-height: 40px;
            border-radius: 3px;
            margin: 0 5px;
            outline: none !important;
        }

        .modal-confirm .btn-info {
            background: #c1c1c1;
        }

            .modal-confirm .btn-info:hover, .modal-confirm .btn-info:focus {
                background: #a8a8a8;
            }

        .modal-confirm .btn-danger {
            background: #f15e5e;
        }

            .modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
                background: #ee3535;
            }

    .trigger-btn {
        display: inline-block;
        margin: 100px auto;
    }
</style>


<link rel="stylesheet" href="~/css/GetAllMediaQuery.css" />

<div class="modal-dialog modal-confirm">
    <div class="modal-content">
        <div class="modal-header">
            <div class="icon-box">
                <i class="material-icons">&#xE5CD;</i>
            </div>
            <h4 class="modal-title">  هل أنت متأكد؟</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        </div>
        <div class="modal-body">
            <p>.   هل تريد حقا حذف هذه السجلات؟ ولا يمكن التراجع عن هذه العملية  </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info" data-dismiss="modal">إلغاء الأمر</button>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">حذف</button>
            </form>

        </div>
    </div>
</div>

School.WebApp/Areas/Manger/Views/Subjects/Details.cshtml
@model School.Data.Entities.Subject

 
@{
    ViewData["Title"] = "تفاصيل المادة الدراسية ";
}


 

<style>
    .label-info {
        font-size: 18px;
        font-weight: 500;
    }

    .data-div {
        margin-top: 20px;
    }

    .data-span {
        font-size: 15px;
        color: #918282;
    }
</style>


<div class="row">
    <div class="col-md-12">

        <div class="row">
            <div class="col-md-6">
                <p class="text-right">
                    <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.Id" style="background-color: #4159AE;color:#fff;font-weight:500;">
                        تعديل
                        <i class="fa-solid fa-plus"></i>
                    </a>
                </p>
            </div>
            <div class="col-md-6">
                <div style="text-align: right; color: #000; font-size: 22px; font-weight: 600; margin-bottom: 40px; border-bottom: 2px dashed ; padding-bottom: 10px;">
                    <span>بيانات المادة الدراسية   </span>
                </div>
            </div>

        </div> 
    </div>

    <div class="col-md-3 text-right">
        <div class="row">
            <div class="col-md-12">
                <span class="label-info">
                  
                 </span>
            </div>
            <div class="col-md-12 data-div">
             </div>
        </div>
    </div>

    <div class="col-md-3 text-right">
        <div class="row">
            <div class="col-md-12">
                <span class="label-info">
                    اسم المادة
                    <i class="fa-solid fa-signature"></i>
                </span>
            </div>
            <div class="col-md-12 data-div">
                <span class="data-span"> @Html.DisplayFor(model => model.Name)  </span>
            </div>
        </div>
    </div>

    <div class="col-md-3 text-right">
        <div class="row">
            <div class="col-md-12">
                <span class="label-info">
                    المادة خاصة بالصف الدراسي
                 </span>
            </div>
            <div class="col-md-12 data-div">
                <span class="data-span">  @Html.DisplayFor(model => model.Class.Name)  </span>
            </div>
        </div>
    </div>

    <div class="col-md-3 text-right">
        <div class="row">
            <div class="col-md-12">
                <span class="label-info">
                    معلم المادة
                 </span>
            </div>
            <div class="col-md-12 data-div">
                <span class="data-span">  @Html.DisplayFor(model => model.Teacher.FullName) </span>
            </div>
        </div>
    </div>




</div>



 

School.WebApp/Areas/Manger/Views/Subjects/GetAll.cshtml
@model School.Data.ViewModels.SubjectViewModel

@{
    ViewData["Title"] = "المواد الدراسية ";
}




<link rel="stylesheet" href="~/assets/TFiles/css/TableListStyle.css" />
<link rel="stylesheet" href="~/css/GetAllMediaQuery.css" />

<p class="text-right">
    <a class="btn btn-info" asp-action="Create" style="background-color: #4159AE;color:#fff;font-weight:500;">
        إنشاء مادة جديدة
        <i class="fa-solid fa-plus"></i>
    </a>
</p>
@using (Html.BeginForm("ExporDataToFile", "Subjects", FormMethod.Post))
{

    <div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
        <button id="btnExportData" type="submit" value="ExportData" name="action">
            <i class="fas fa-file-download"> Export Data </i>
        </button>
    </div>
    <div class="col-md-5">
        <label>
            <input id="ExportPdf" name="Export" type="radio"
                   value="Pdf" />
            <i class="far fa-file-pdf">  Export To Pdf</i>
        </label>
    </div>


}

<table id="myTable" class="table dt-responsive  " style="width:100%">
    <thead class="thead_dark">
        <tr style=" background-color: #8c9cd0; border: 0px; color: #fff;">
            <th class="text-right">الإجراءات</th>


            <th class="text-right mobile-hidden">
                مدرس المادة
            </th>
            <th class="text-right">
                الصف
            </th>
            <th class="text-right">
                اسم المادة
            </th>



        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.SubjectList)
        {
            <tr>

                <td class="text-right">

                    <div class="dropdown">
                        <button class="btn btn-secondary"
                                type="button"
                                id="dropdownMenuButton"
                                data-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false" style="background-color: #fff;border:0px;">
                            <i class="fa-solid fa-ellipsis" style="color: #000;"></i>
                        </button>

                        <div class="dropdown-menu text-right"
                             aria-labelledby="dropdownMenuButton" style="">


                            <a class="dropdown-item" asp-action="Edit" asp-controller="Subjects" asp-route-id="@item.Id">
                                تعديل
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a class="dropdown-item" asp-action="Details" asp-controller="Subjects" asp-route-id="@item.Id">
                                عرض التفاصيل
                                <i class="fa-solid fa-list"></i>
                            </a>
                            <a class="dropdown-item" asp-action="Delete" asp-controller="Subjects" asp-route-id="@item.Id">
                                حذف المادة
                                <i class="fa-solid fa-trash"></i>
                            </a>

                        </div>
                    </div>
                </td>


                <td class="text-right mobile-hidden">
                    @Html.DisplayFor(modelItem => item.Teacher.FullName)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Class.Name)
                </td>

                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>



            </tr>
        }
    </tbody>
</table>