School.WebApp/Areas/Manger/Controllers/SkillsBehaviorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApp.Areas.Manger.Controllers
{
    [Area("Manger")]
    public class SkillsBehaviorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _HttpContextAccessor;
        public string UserEmail;

        public SkillsBehaviorsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _HttpContextAccessor = httpContextAccessor;
            UserEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;

        }



        public async Task<IActionResult> GetStudentSkillsBehaviors(int? id)
        {
            var model = new SkillsBehaviorViewModel();
            if (id == null)
            {
                return NotFound();
            }
            model.Decisions = _context.Decisions.FirstOrDefault();
            model.SkillsBehaviorList = _context.SkillsBehavior
            .Include(w => w.Class)
            .Include(w => w.Student)
            .Include(w => w.Subject)
            .Include(w => w.Teacher)
            .Where(m => m.StudentId == id)
            .ToList();
            if (model.SkillsBehaviorList.Any() == true)
            {
                model.IsActive = true;
            }
            else
            {
                model.IsActive = false;
            }

            return View(model);
        }



        [HttpPost]
        public IActionResult ExporDataToFile()
        {
            var dictioneryexportType = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            var exportType = dictioneryexportType["Export"];
            var model = GetDataDetail();
            switch (exportType)
            {


                case "Pdf":
                    ExportToPdf(model);
                    break;


            }
            return null;
        }

        private void ExportToPdf(DataTable model)
        {

            if (model.Rows.Count > 0)
            {
                string fontLoc = @"./ARIALUNI.ttf"; // make sure to have the correct path to the font file

                int pdfRowIndex = 1;
                string filename = "عرض التقييمات السلوكية " + DateTime.Now.ToString("dd-MM-yyyy hh_mm_s_tt");
                string filepath = MyServer.MapPath("\\") + "" + filename + ".pdf";
                Document document = new Document(PageSize.A4, 5f, 5f, 10f, 10f);
                FileStream fs = new FileStream(filepath, FileMode.Create);
                PdfWriter writer = PdfWriter.GetInstance(document, fs);
                document.Open();

                Font font1 = FontFactory.GetFont(FontFactory.COURIER_BOLD, 13);
                Font font2 = FontFactory.GetFont(FontFactory.COURIER, 8);
                BaseFont bf = BaseFont.CreateFont(fontLoc, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                Font f = new Font(bf, 8);

                Font fHeader = new Font(bf, 11);


                float[] columnDefinitionSize = { 2f, 2f, 2f, 2f, 2f, 2f, 2f};
                PdfPTable table;
                PdfPCell cell;

                table = new PdfPTable(8)
                {
                    WidthPercentage = 100
                };

                cell = new PdfPCell
                {
                    BackgroundColor = new BaseColor(0xC0, 0xC0, 0xC0)
                };
                table.RunDirection = PdfWriter.RUN_DIRECTION_RTL;

                table.AddCell(new Phrase("اسم البند ", fHeader));
                table.AddCell(new Phrase("اسم الطالب   ", fHeader));
                table.AddCell(new Phrase("الصف  ", fHeader));
                table.AddCell(new Phrase("المادة  ", fHeader));

                table.AddCell(new Phrase(" اسم المعلم  ", fHeader));
                table.AddCell(new Phrase("الشهر  ", fHeader));
                table.AddCell(new Phrase("التقييم ", fHeader)); 


                foreach (DataRow data in model.Rows)
                {
                     table.AddCell(new Phrase(data["Name"].ToString(), f));
                    table.AddCell(new Phrase(data["Student"].ToString(), f));
                    table.AddCell(new Phrase(data["Class"].ToString(), f));
                    table.AddCell(new Phrase(data["Subject"].ToString(), f));
                    table.AddCell(new Phrase(data["Teacher"].ToString(), f));
                    table.AddCell(new Phrase(data["Duration"].ToString(), f));
                    table.AddCell(new Phrase(data["CompletionType"].ToString(), f));
 

                    pdfRowIndex++;
                }
                //Response.ContentEncoding = System.Text.Encoding.UTF8;


                document.Add(table);
                document.Close();
                document.CloseDocument();
                document.Dispose();
                writer.Close();
                writer.Dispose();
                fs.Close();
                fs.Dispose();

                FileStream sourceFile = new FileStream(filepath, FileMode.Open);
                float fileSize = 0;
                fileSize = sourceFile.Length;
                byte[] getContent = new byte[Convert.ToInt32(Math.Truncate(fileSize))];
                sourceFile.Read(getContent, 0, Convert.ToInt32(sourceFile.Length));
                sourceFile.Close();
                Response.Clear();
                Response.Headers.Clear();
                Response.ContentType = "application/pdf";
                Response.Headers.Add("Content-Length", getContent.Length.ToString());
                Response.Headers.Add("Content-Disposition", "attachment; filename=" + filename + ".pdf;");
                Response.Body.WriteAsync(getContent);
                Response.Body.Flush();
            }
        }
        private DataTable GetDataDetail()
        {
            var ModelList = _context.SkillsBehavior
            .Include(w => w.Subject)
            .Include(w => w.Class)
            .Include(w => w.Teacher)
            .Include(w => w.Duration) 
            .Include(w => w.CompletionType)
            .Include(w => w.Student)
            
            .ToList();
             


            DataTable dtProduct = new DataTable("عرض صفوف المدرسة ");
            dtProduct.Columns.AddRange(new DataColumn[] {
                 new DataColumn("Name"),
                new DataColumn("Student"),
                new DataColumn("Class"),
                new DataColumn("Subject"),
                new DataColumn("Teacher"),
                new DataColumn("Duration"),
                new DataColumn("CompletionType") 

            });
            foreach (var model in ModelList)
            {
                dtProduct.Rows.Add(model.Name, model.Student.FullName, model.Class.Name,
                                   model.Subject.Name, model.Teacher.FullName, model.Duration.Name, model.CompletionType.Name
                                   );
            }

            return dtProduct;
        }




        private bool SkillsBehaviorExists(int id)
        {
            return _context.SkillsBehavior.Any(e => e.Id == id);
        }
    }
}

School.WebApp/Areas/StudentUser/Controllers/SkillsBehaviorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApp.Areas.StudentUser.Controllers
{
    [Area("StudentUser")]
    [Authorize(Roles = "StudentRole")]
    public class SkillsBehaviorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public string StudentEmail;
        public int StudentUserId;
        private readonly IHttpContextAccessor _HttpContextAccessor;
        public SkillsBehaviorsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _HttpContextAccessor = httpContextAccessor;
            StudentEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;
            StudentUserId = _context.Student.Where(d => d.EmailAddress == StudentEmail).Select(d => d.Id).FirstOrDefault();

        }



        public async Task<IActionResult> Index()
        {
            var model = new SkillsBehaviorViewModel();

            model.Decisions = _context.Decisions.FirstOrDefault();
            model.SkillsBehaviorList = _context.SkillsBehavior
            .Include(w => w.Class)
            .Include(w => w.Student)
            .Include(w => w.Subject)
            .Include(w => w.Teacher)
            .Include(d => d.CompletionType)
            .Where(m => m.StudentId == StudentUserId)
            .ToList();
            if (model.SkillsBehaviorList.Any() == true)
            {
                model.IsActive = true;
            }
            else
            {
                model.IsActive = false;
            }

            return View(model);
        }



        private bool SkillsBehaviorExists(int id)
        {
            return _context.SkillsBehavior.Any(e => e.Id == id);
        }
    }
}

School.WebApp/Areas/TeacherUser/Controllers/SkillsBehaviorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApp.Areas.TeacherUser.Controllers
{
    [Area("TeacherUser")]
    public class SkillsBehaviorsController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _HttpContextAccessor;
        public string UserEmail;
        public int TeacherUserId;

        public SkillsBehaviorsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _HttpContextAccessor = httpContextAccessor;
            UserEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;
            TeacherUserId = _context.Teacher.Where(d => d.EmailAddress == UserEmail).Select(d => d.Id).FirstOrDefault();

        }



        public async Task<IActionResult> GetStudentSkillsBehaviors(int? id)
        {
            var model = new SkillsBehaviorViewModel();
            if (id == null)
            {
                return NotFound();
            }
            model.Decisions = _context.Decisions.FirstOrDefault();
            model.SkillsBehaviorList = _context.SkillsBehavior
            .Include(w => w.Class)
            .Include(w => w.Student)
            .Include(w => w.Subject)
            .Include(w => w.Teacher).Include(w => w.CompletionType)
            .Where(m => m.StudentId == id)
            .ToList();
            if (model.SkillsBehaviorList.Any() == true)
            {
                model.IsActive = true;
            }
            else
            {
                model.IsActive = false;
            }

            return View(model);
        }

        public IActionResult Create(int? ClassID)
        {
            var model = new SkillsBehaviorViewModel();
            model.DurationDrop = _context.Duration.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name });
            model.CompletionTypeDrop = _context.CompletionType.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name });
            model.SubjectsDrop = _context.Subject.Where(d => d.TeacherId == TeacherUserId).Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name });
            model.StudentDrop = _context.Student.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.FullName });

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SkillsBehaviorViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.SkillsBehavior.ClassId = _context.Student.Where(d => d.Id == model.SkillsBehavior.StudentId).Select(s => s.ClassId).FirstOrDefault();
                model.SkillsBehavior.TeacherId = TeacherUserId;
                model.CreatedAt = DateTime.Now;
                model.CreatedBy = UserEmail;
                _context.Add(model.SkillsBehavior);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Classes");
            }

            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = new SkillsBehaviorViewModel();
            model.DurationDrop = _context.Duration.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name });
            model.CompletionTypeDrop = _context.CompletionType.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name });
            model.SubjectsDrop = _context.Subject.Where(d => d.TeacherId == TeacherUserId).Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name });
            model.StudentDrop = _context.Student.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.FullName });



            if (model.SkillsBehavior == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SkillsBehaviorViewModel model)
        {
            if (id != model.SkillsBehavior.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    model.SkillsBehavior.UpdatedAt = DateTime.Now;
                    model.SkillsBehavior.UpdatedBy = UserEmail;

                    _context.Update(model.SkillsBehavior);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkillsBehaviorExists(model.SkillsBehavior.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Classes");
            }
            return View(model);
        }



        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.SkillsBehavior
                .Include(m => m.Class)
                .Include(m => m.Student)
                .Include(m => m.Subject)
                .Include(m => m.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // POST: TeacherUser/Marks1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mark = await _context.SkillsBehavior.FindAsync(id);
            mark.IsDelete = true;
            _context.SkillsBehavior.Update(mark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool SkillsBehaviorExists(int id)
        {
            return _context.SkillsBehavior.Any(e => e.Id == id);
        }
    }
}

School.WebApp/Areas/Manger/Views/SkillsBehaviors/GetStudentSkillsBehaviors.cshtml
@model School.Data.ViewModels.SkillsBehaviorViewModel

@{
    ViewData["Title"] = "سجل التقييم السلوكي للطالب ";
}


<style>
    .subrow {
        border-top: 2px solid;
        padding-top: 10px;
    }

    .header-t {
        padding-top: 25px;
        padding-bottom: 15px;
        color: #000;
        text-align: center;
        font-weight: 600;
    }

    .header-p-t {
        font-weight: 500;
        color: #000;
    }

    p {
        font-family: dkmmljn.kjn !important;
        font-size: 1.1em;
        font-weight: 300;
        line-height: 1.7em;
        color: #000;
    }

    .data-info-sec {
        padding-bottom: 12px !important;
        padding-top: 10px !important;
        border-bottom: 1px solid;
    }
</style>
<link rel="stylesheet" href="~/css/GetAllMediaQuery.css" />


@if (Model.IsActive == true)
{
<div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
    @using (Html.BeginForm("ExporDataToFile", "SkillsBehaviors", FormMethod.Post))
    {
        <button id="btnExportData" type="submit" value="ExportData" name="action">
            <i class="fas fa-file-download">  تصدير </i>
        </button>

        <br />
        <br />


        <div class="col-md-5">
            <label>
                <input id="ExportPdf" name="Export" type="radio"
                       value="Pdf" />
                <i class="far fa-file-pdf">  Export To Pdf</i>
            </label>
        </div>
    }
</div>
}


<div class="row" style="font-family: 'Changa', sans-serif;    ">
    <div class="container-fluid">
        <div class="row text-right" style=" border: 2px solid;">
            <div class="col-md-3" style=" border-right: 1px solid;">
                <div class="header-t row" style="padding-bottom: 0px; padding-top: 10px;">
                    <div class="col-3">
                        <p class="header-p-t"> إنجاز سريع </p>
                    </div>
                    <div class="col-3">
                        <p class="header-p-t"> إنجاز مساعدة </p>
                    </div>
                    <div class="col-3">
                        <p class="header-p-t"> إنجاز عادي </p>
                    </div>
                    <div class="col-3">
                        <p class="header-p-t"> لم ينجز  </p>
                    </div>

                </div>
                <div class="row subrow">
                    @if (Model.IsActive == true)
                    {
                        @foreach (var item in Model.SkillsBehaviorList)
                        {
                            @if (item.CompletionTypeId == 1) // إنجاز
                            {
                                <div class="col-3 data-info-sec">
                                    <i class="fa-solid fa-check"></i>
                                </div>
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec"></div>

                            }
                            else if (item.CompletionTypeId == 2)
                            {
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec">
                                    <i class="fa-solid fa-check"></i>
                                </div>

                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec"></div>

                            }
                            else if (item.CompletionTypeId == 3)
                            {
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec">
                                    <i class="fa-solid fa-check"></i>
                                </div>
                                <div class="col-3 data-info-sec"></div>

                            }
                            else if (item.CompletionTypeId == 4)
                            {
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec"></div>
                                <div class="col-3 data-info-sec">
                                    <i class="fa-solid fa-check"></i>
                                </div>
                            }

                        }

                    }

                </div>
            </div>
            <div class="col-md-7" style=" border-right: 2px solid;">
                <p class="header-t">  البنود </p>

                <div class="row subrow">


                    @if (Model.IsActive == true)
                    {

                        @foreach (var item in Model.SkillsBehaviorList)
                        {
                            <div class="col-md-12 data-info-sec">
                                @item.Name
                            </div>
                        }

                    }
                    else
                    {
                        <p class="text-center" style=" padding-bottom: 12px; padding-left: 9cm;">
                            لم يتم إضافة مهارات دراسية للطالب
                        </p>
                    }
                </div>

            </div>
            <div class="col-md-2">
                <p class="header-t"> # </p>
                <div class="row subrow">
                    @if (Model.IsActive == true)
                    {
                        @foreach (var item in Model.SkillsBehaviorList)
                        {
                            <div class="col-md-12 data-info-sec">
                                @item.Id
                            </div>
                        }
                    }

                </div>
            </div>
        </div>
    </div>
</div>