School.WebApplication/Areas/MangerUser/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.DataAccess;
using School.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Data;

namespace School.WebApplication.Areas.MangerUser.Controllers
{
    [Area("MangerUser")]
    [Authorize/*(Roles = "Manger")*/]
    public class ClassesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClassesController(ApplicationDbContext context)
        {
            _context = context;
        }


        [HttpPost]
        public IActionResult ExporDataToFile()
        {
            var dictioneryexportType = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            var exportType = dictioneryexportType["Export"];
            var Class = GetClassDetail();
            switch (exportType)
            {


                case "Pdf":
                    ExportToPdf(Class);
                    break;


            }
            return null;
        }




        private void ExportToPdf(DataTable @class)
        {

            if (@class.Rows.Count > 0)
            {
                int pdfRowIndex = 1;
                string filename = "الفصول الدراسية -" + DateTime.Now.ToString("dd-MM-yyyy hh_mm_s_tt");
                string filepath = MyServer.MapPath("\\") + "" + filename + ".pdf";
                Document document = new Document(PageSize.A4, 5f, 5f, 10f, 10f);
                FileStream fs = new FileStream(filepath, FileMode.Create);
                PdfWriter writer = PdfWriter.GetInstance(document, fs);
                document.Open();

                Font font1 = FontFactory.GetFont(FontFactory.COURIER_BOLD, 15);
                Font font2 = FontFactory.GetFont(FontFactory.COURIER, 8);

                float[] columnDefinitionSize = { 2F, 5F, 2F, 5F };
                PdfPTable table;
                PdfPCell cell;

                table = new PdfPTable(columnDefinitionSize)
                {
                    WidthPercentage = 100
                };

                cell = new PdfPCell
                {
                    BackgroundColor = new BaseColor(0xC0, 0xC0, 0xC0)
                };

                table.AddCell(new Phrase("Id", font1));
                table.AddCell(new Phrase("Name", font1));
                table.HeaderRows = 1;

                foreach (DataRow data in @class.Rows)
                {
                    table.AddCell(new Phrase(data["Id"].ToString(), font2));
                    table.AddCell(new Phrase(data["Name"].ToString(), font2));

                    pdfRowIndex++;
                }
                //Response.ContentEncoding = System.Text.Encoding.UTF8;


                document.Add(table); 
                document.Close();
                document.CloseDocument();
                document.Dispose();
                writer.Close();
                writer.Dispose();
                fs.Close();
                fs.Dispose();

                FileStream sourceFile = new FileStream(filepath, FileMode.Open);
                float fileSize = 0;
                fileSize = sourceFile.Length;
                byte[] getContent = new byte[Convert.ToInt32(Math.Truncate(fileSize))];
                sourceFile.Read(getContent, 0, Convert.ToInt32(sourceFile.Length));
                sourceFile.Close();
                Response.Clear();
                Response.Headers.Clear();
                Response.ContentType = "application/pdf";
                Response.Headers.Add("Content-Length", getContent.Length.ToString());
                Response.Headers.Add("Content-Disposition", "attachment; filename=" + filename + ".pdf;");
                Response.Body.WriteAsync(getContent);
                Response.Body.Flush();
            }
        }
        public async Task<IActionResult> Index()
        {
            var model = new ClassViewModel()
            {
                ClassList = _context.Classes.ToList(),
                TeacherList = _context.Teacher.ToList(),
                Class = new Class(),
                Teacher = new School.Data.Entities.Teacher(),

            };

            return View(model);
        }
        public IActionResult GetTeachers(int? id)
        {
            List<int> TeacherIDs = new List<int>();
            List<Teacher> TeacherList = new List<Teacher>();


            if (id == null)
            {
                return NotFound();
            }

            ClassViewModel model = new ClassViewModel()
            {
                Class = _context.Classes.Where(d => d.Id == id).FirstOrDefault(),

            };
            TeacherIDs = _context.Subject.Where(d => d.ClassId == id).Select(h => h.TeacherId).ToList();

            foreach (var item in TeacherIDs)
            {
                TeacherList.Add(_context.Teacher.Where(d => d.Id == item).FirstOrDefault());
            }


            model.TeacherList = TeacherList;
            model.Capacity = model.TeacherList.Count();



            if (TeacherIDs.Count() > 0)
            {
                model.IsActive = true;
            }


            if (model.Class == null)
            {
                return NotFound();
            }

            return View(model);
        }
        public IActionResult GetStudents(int? id)
        {
            List<int> StudentIDs = new List<int>();
            List<Student> StudentList = new List<Student>();


            if (id == null)
            {
                return NotFound();
            }

            ClassViewModel model = new ClassViewModel()
            {
                Class = _context.Classes.Where(d => d.Id == id).FirstOrDefault(),
                //StudentList = _context.Student.Where(d => d.ClassId == id).ToList(),

            };
            StudentIDs = _context.Student.Where(d => d.ClassId == id).Select(h => h.Id).ToList();

            foreach (var item in StudentIDs)
            {
                StudentList.Add(_context.Student.Where(d => d.Id == item).FirstOrDefault());
            }
            model.StudentList = StudentList;
            model.Capacity = model.StudentList.Count();

            if (model.Class == null)
            {
                return NotFound();
            }

            return View(model);
        }
        public IActionResult GetSubjects(int? id)
        {
            List<int> SubjectIDs = new List<int>();
            List<Subject> SubjectList = new List<Subject>();


            if (id == null)
            {
                return NotFound();
            }

            ClassViewModel model = new ClassViewModel()
            {
                Class = _context.Classes.Where(d => d.Id == id).FirstOrDefault(),

            };
            SubjectIDs = _context.Subject.Where(d => d.ClassId == id).Select(h => h.Id).ToList();

            foreach (var item in SubjectIDs)
            {
                SubjectList.Add(_context.Subject.Where(d => d.Id == item).Include(c => c.Teacher).Include(d => d.Class).FirstOrDefault());
            }
            model.SubjectList = SubjectList;
            model.Capacity = model.SubjectList.Count();

            if (model.Class == null)
            {
                return NotFound();
            }

            return View(model);
        }





        private DataTable GetClassDetail()
        {
            var Class = _context.Classes.ToList();

            DataTable dtProduct = new DataTable("عرض صفوف المدرسة ");
            dtProduct.Columns.AddRange(new DataColumn[2] {
                new DataColumn("Id"),
                new DataColumn("Name")
            });
            foreach (var @Classes in Class)
            {
                dtProduct.Rows.Add(@Classes.Id ,@Classes.Name );
            }

            return dtProduct;
        }

    }
}

School.WebApplication/Areas/MangerUser/Controllers/MarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApplication.Areas.MangerUser.Controllers
{
    //[Area("Manger")]
    [Authorize/*(Roles = "Manger")*/]
    public class MarksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MarksController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Mark.Include(m => m.Class).Include(m => m.Student).Include(m => m.Subject).Include(m => m.Teacher);
            return View(await applicationDbContext.ToListAsync());
        }
         
        public IActionResult Find(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MarkViewModel model = new MarkViewModel()
            {
                   MarkList = _context.Mark.Include(d => d.Class).Include(d => d.FinalSkillsType)
                   .Include(d => d.Student).Include(d => d.Teacher)
                       .Include(d => d.MSkillsType).Include(d => d.FSkillsType).Include(d => d.Subject)
                   .Where(d => d.StudentId == id).ToList(),
                   Student = _context.Student.Where(d => d.Id == id).FirstOrDefault()                   

            };


          

            //if (model.MarkList.Count()>0)
            //{ 
            //    model.TeacherName = _context.Mark.Where(d => d.Id == MarkIDs[0]).Select(d => d.Teacher.FullName).FirstOrDefault();
            //    model.StudentName = _context.Mark.Where(d => d.Id == MarkIDs[0]).Select(d => d.Student.FullName).FirstOrDefault();
            //    model.SubjectName = _context.Mark.Where(d => d.Id == MarkIDs[0]).Select(d => d.Subject.Name).FirstOrDefault();
            //}
            //else
            //{
            //    model.TeacherName = "";
            //    model.StudentName = "";
            //    model.SubjectName = "";
            //} 

            return View(model);
        }

 
    }
}

School.WebApplication/Areas/MangerUser/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.DataAccess;

namespace School.WebApplication.Areas.MangerUser.Controllers
{
    [Authorize/*(Roles = "Manger")*/]
    //[Area("Manger")]
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeachersController(ApplicationDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _context.Teacher.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

   

    }
}

School.WebApplication/Areas/StudentUser/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApplication.Areas.StudentUser.Controllers
{
    //[Authorize(Roles="Student")]
    [Area("StudentUser")]
    public class SkillssController : Controller
    {
        private readonly ApplicationDbContext _context;
        public string StudentEmail;
        public int StudentUserId;
        private readonly IHttpContextAccessor _HttpContextAccessor;

         
        public SkillssController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _HttpContextAccessor = httpContextAccessor;
            StudentEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;
            StudentUserId = _context.Student.Where(d => d.EmailAddress == StudentEmail).Select(d => d.Id).FirstOrDefault();

        }

        

        public IActionResult Index()
        {
            List<int> SkillsIDs = new List<int>();
            List<Skills> SkillsList = new List<Skills>();
            SkillsViewModel model = new SkillsViewModel();
            if (StudentUserId == null)
            {
                return NotFound();
            }
            SkillsIDs = _context.Skills.Where(d => d.StudentId == StudentUserId).Select(h => h.Id).ToList();// get student Ids from class   
            foreach (var item in SkillsIDs)
            {
                SkillsList.Add(_context.Skills.Include(d => d.Student).Include(d => d.Duration).Include(d => d.SkillsType).Include(d => d.Subject).Include(d => d.Teacher).Where(d => d.Id == item).FirstOrDefault());
            }
            if (SkillsIDs.Count() > 0)
            {
                model.SkillsList = SkillsList;
                model.IsActive = true;
              }
            else
            {
                model.IsActive = false;
            }

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }








        private bool SkillsExists(int id)
        {
            return _context.Skills.Any(e => e.Id == id);
        }
    }
}

School.WebApplication/Areas/StudentUser/Controllers/WeaknessStrengthsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data.Entities;
using School.Data.ViewModels;
using School.DataAccess;

namespace School.WebApplication.Areas.StudentUser.Controllers
{
    [Area("StudentUser")]
    public class SkillsSuggestionssController : Controller
    {
       
        private readonly ApplicationDbContext _context;
        public string StudentEmail;
        public int StudentUserId;
        private readonly IHttpContextAccessor _HttpContextAccessor;


        public SkillsSuggestionssController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _HttpContextAccessor = httpContextAccessor;
            StudentEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;
            StudentUserId = _context.Student.Where(d => d.EmailAddress == StudentEmail).Select(d => d.Id).FirstOrDefault();

        }


        public IActionResult Index()
        {
            List<int> WSIDs = new List<int>();
            List<SkillsSuggestions> SkillsSuggestionsList = new List<SkillsSuggestions>();
            SkillsSuggestionsViewModel model = new SkillsSuggestionsViewModel();
            if (StudentUserId == null)
            {
                return NotFound();
            }
            WSIDs = _context.Student.Where(d => d.Id == StudentUserId).Select(h => h.Id).ToList();// get student Ids from class   
            foreach (var item in WSIDs)
            {
                SkillsSuggestionsList.Add(_context.SkillsSuggestions.Include(d => d.Student).Include(d => d.Subject).Include(d => d.Teacher).Where(d => d.StudentId == item).FirstOrDefault());
            }
            if (WSIDs.Count() > 0)
            {
                model.SkillsSuggestionsList = SkillsSuggestionsList;
                model.IsActive = true;
            }
            else
            {
                model.IsActive = false;
            }

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }





        private bool SkillsSuggestionsExists(int id)
        {
            return _context.SkillsSuggestions.Any(e => e.Id == id);
        }
    }
}

School.WebApplication/Areas/MangerUser/Views/Classes/GetStudents.cshtml
@model School.Data.ViewModels.ClassViewModel

@{
    ViewData["Title"] = "عرض طلاب الفصل";
}


<style>
    .dropdown {
        padding: 0px;
    }

    table.dataTable thead > tr > th.sorting_asc:before, table.dataTable thead > tr > th.sorting_desc:after, table.dataTable thead > tr > td.sorting_asc:before, table.dataTable thead > tr > td.sorting_desc:after {
        color: #0E268C;
        opacity: 1;
        font-size: 20px;
    }

    .table-hover tbody tr:hover {
        color: #212529;
        background-color: rgba(0,0,0,.075);
    }

    .table-hover tbody tr {
        background-color: #fff;
    }

    table.dataTable tbody th, table.dataTable tbody td {
        padding-left: 15px;
        padding-top: 15px;
    }

    table.dataTable thead > tr > th.sorting, table.dataTable thead > tr > th.sorting_asc, table.dataTable thead > tr > th.sorting_desc, table.dataTable thead > tr > th.sorting_asc_disabled, table.dataTable thead > tr > th.sorting_desc_disabled, table.dataTable thead > tr > td.sorting, table.dataTable thead > tr > td.sorting_asc, table.dataTable thead > tr > td.sorting_desc, table.dataTable thead > tr > td.sorting_asc_disabled, table.dataTable thead > tr > td.sorting_desc_disabled {
        cursor: pointer;
        position: relative;
        padding-right: 26px;
        color: #fff;
    }

    .dropdown-item {
        display: block;
        width: 100%;
        padding: 0.5rem 1rem;
        clear: both;
        font-weight: 400;
        color: #fff;
        text-align: inherit;
        white-space: nowrap;
        background-color: transparent;
        border: 0;
    }

    .dropdown-menu {
        border-top-left-radius: 15px;
        position: absolute;
        will-change: transform;
        background-color: rgb(14, 38, 140);
        border: 2px solid rgb(14, 38, 140);
        top: 0px;
        opacity: 0.7;
        left: 0px;
        transform: translate3d(0px, -185px, 0px);
    }

    .dropdown-item.active, .dropdown-item:active {
        color: rgb(14, 38, 140);
        text-decoration: none;
        background-color: #fff;
    }


    .dropdown-item.active, .dropdown-item:hover {
        color: rgb(14, 38, 140) !important;
        text-decoration: none;
        background-color: #fff !important;
    }

    .dataTables_wrapper .dataTables_length {
        float: left;
        display: none;
    }

    .dataTables_wrapper .dataTables_filter {
        float: left;
        text-align: left;
        direction: rtl;
    }

    table.dataTable thead > tr > th.sorting, table.dataTable thead > tr > th.sorting_asc, table.dataTable thead > tr > th.sorting_desc, table.dataTable thead > tr > th.sorting_asc_disabled, table.dataTable thead > tr > th.sorting_desc_disabled, table.dataTable thead > tr > td.sorting, table.dataTable thead > tr > td.sorting_asc, table.dataTable thead > tr > td.sorting_desc, table.dataTable thead > tr > td.sorting_asc_disabled, table.dataTable thead > tr > td.sorting_desc_disabled {
        cursor: pointer;
        position: relative;
        padding-right: 26px;
        color: #fff;
        border-top: 0px;
    }

    .small-info {
        background-color: #8c9cd0;
        color: #fff;
        padding: 3px;
        border-radius: 3px;
    }

    .dataTables_wrapper .dataTables_filter input {
        border: 1px solid #aaa;
        border-radius: 3px;
        padding: 5px;
        background-color: transparent;
        margin-left: 3px;
        margin-right: 10px !important;
    }

    label {
        display: inline-block;
        margin-bottom: 0.5rem;
        color: #4159AE;
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
        color: #fff !important;
        background-color: #0E268C;
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current {
        color: #fff !important;
        background-color: #0E268C;
    }
</style>
<style>


    .content {
        padding: 7rem 0;
    }


    .owl-1 .owl-nav {
        width: 100%;
        position: absolute;
        top: 50%;
    }

        .owl-1 .owl-nav .owl-next,
        .owl-1 .owl-nav .owl-prev {
            border: 1px solid red;
            z-index: 92;
            position: absolute;
            top: 50%;
        }

            .owl-1 .owl-nav .owl-next:active, .owl-1 .owl-nav .owl-next:focus,
            .owl-1 .owl-nav .owl-prev:active,
            .owl-1 .owl-nav .owl-prev:focus {
                outline: none;
            }

            .owl-1 .owl-nav .owl-next span,
            .owl-1 .owl-nav .owl-prev span {
                color: #fff;
            }

                .owl-1 .owl-nav .owl-next span:before,
                .owl-1 .owl-nav .owl-prev span:before {
                    font-size: 40px !important;
                }

        .owl-1 .owl-nav .owl-next {
            border: 4px solid blue;
            right: 20px;
        }

        .owl-1 .owl-nav .owl-prev {
            left: 20px;
        }

    .owl-1 .owl-dots {
        position: absolute;
        bottom: 40px;
        left: 50%;
        -webkit-transform: translateX(-50%);
        -ms-transform: translateX(-50%);
        transform: translateX(-50%);
    }

        .owl-1 .owl-dots .owl-dot {
            background: none;
            display: inline-block;
        }

            .owl-1 .owl-dots .owl-dot > span {
                display: inline-block;
                width: 7px;
                height: 7px;
                border-radius: 50%;
                background: rgba(255, 255, 255, 0.5);
                margin: 4px;
            }

            .owl-1 .owl-dots .owl-dot.active > span {
                background: white;
            }

            .owl-1 .owl-dots .owl-dot:active, .owl-1 .owl-dots .owl-dot:focus {
                outline: none;
            }

    .media-29101 .img {
        -webkit-box-flex: 0;
        -ms-flex: 0 0 50%;
        flex: 0 0 50%;
    }

    .media-29101 .text {
        padding: 50px;
    }

    @@media (max-width: 991.98px) {
        .media-29101 .text {
            padding: 20px;
            width: 100%;
        }
    }

    .media-29101 .text .category {
        color: #adb5bd;
        text-transform: uppercase;
        font-size: 12px;
        font-weight: bold;
        letter-spacing: .2rem;
    }

    .media-29101 .text h2 {
        font-family: "Playfair Display", times, serif;
        font-size: 2rem;
        line-height: 1.3;
        margin-bottom: 30px;
    }

        .media-29101 .text h2 a {
            color: #000;
        }

    .carousel-nav {
        width: 100%;
        border-bottom: 1px solid #ccc;
        margin-bottom: 40px;
    }

        .carousel-nav a {
            color: #999;
            padding: 20px;
            text-align: center;
            display: inline-block;
        }

            .carousel-nav a:hover {
                color: #000;
            }

            .carousel-nav a.active {
                color: #000;
            }

                .carousel-nav a.active:before {
                    content: "";
                    bottom: -1px;
                    left: 0;
                    right: 0;
                    position: absolute;
                    border-bottom: 1px solid #000;
                }
</style>





<div class="row" style="margin-top:-4.5rem !important ">
    <div class="col-12 text-right" style="margin-bottom: 50px;padding: 30px;
              background-color: #fff;box-shadow: rgb(0 0 0 / 10%) 0px 5px 12px;">
        <div style="color: #1459AE; font-weight: 700; font-size: 18px; margin-bottom: 35px; ">
            <span>
                هذه الصفحة تعرض طلاب الصف  :     <strong>@Model.Class.Name</strong>
            </span>
        </div> 
    </div>
</div>



@if (Model.StudentList.Count() > 0)
{
    <table id="myTable" class="table dt-responsive  " style="width:100%">
        <thead class="thead_dark">
            <tr style=" background-color: #8c9cd0; border: 0px; color: #fff;">
                <th class="text-right"> الإجراءات </th>

                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Student.PhoneNumber)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Student.EmailAddress)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Student.FullName)
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.StudentList)
            {
                <tr>
                    <td class="text-right">
                        <div class="dropdown">
                            <button class="btn btn-secondary"
                                    type="button"
                                    id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="false" style="background-color: #fff;border:0px;">
                                <i class="fa-solid fa-ellipsis" style="color: #000;"></i>
                            </button>

                            <div class="dropdown-menu text-right"
                                 aria-labelledby="dropdownMenuButton" style="">

                                <a class="dropdown-item" asp-controller="Marks" asp-action="Find" asp-route-id="@item.Id" asp-area="Manger">سجل العلامات  </a> |
                                <a class="dropdown-item" asp-controller="Skillss" asp-action="Find" asp-route-id="@item.Id" asp-area="Manger">سجل التقييم للطالب </a> |
                                <a class="dropdown-item" asp-controller="SkillsStudentBehaviors" asp-action="Find" asp-route-id="@item.Id" asp-area="Manger">سجل التقييم السلوكي للطالب </a> |
                                <a class="dropdown-item" asp-controller="SkillsSuggestionss" asp-action="Find" asp-route-id="@item.Id" asp-area="Manger">مواطن الضعف والقوة للطالب</a> |

                            </div>
                        </div>
                    </td>



                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>


                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.EmailAddress)
                    </td>


                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>


                </tr>
            }
        </tbody>
    </table>

}
else
{
    <p>لم يتم إضافة طلاب للفصل حتى الأن  </p>
}

School.WebApplication/Areas/MangerUser/Views/Classes/Index.cshtml
@model School.Data.ViewModels.ClassViewModel

@{
    ViewData["Title"] = "عرض الصفوف المدرسية ";
}


<link rel="stylesheet" href="~/assets/TFiles/css/TableListStyle.css" />




@using (Html.BeginForm("ExporDataToFile", "Classes", FormMethod.Post))
{

    <div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
        <button id="btnExportData" type="submit" value="ExportData" name="action">
            <i class="fas fa-file-download"> Export Data </i>
        </button>
    </div>

    <div class="col-md-3">
        <label>
            <input id="ExportPdf" name="Export" type="radio"
                   value="Pdf" />
            <i class="far fa-file-pdf">  Export To Pdf</i>
        </label>
    </div>


}




<table id="myTable" class="table dt-responsive  " style="width:100%">
    <thead class="thead_dark">
        <tr style=" background-color: #8c9cd0; border: 0px; color: #fff;">
            <th class="text-right">الإجراءات</th>


            <th class="text-right">
                @Html.DisplayNameFor(model => model.Class.Name)
            </th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ClassList)
        {
            <tr>

                <td class="text-right">

                    <div class="dropdown">
                        <button class="btn btn-secondary"
                                type="button"
                                id="dropdownMenuButton"
                                data-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false" style="background-color: #fff;border:0px;">
                            <i class="fa-solid fa-ellipsis" style="color: #000;"></i>
                        </button>

                        <div class="dropdown-menu text-right"
                             aria-labelledby="dropdownMenuButton" style="">
                            <a class="dropdown-item" asp-action="GetStudents" asp-area="Manger" asp-route-id="@item.Id"> عرض طلاب الفصل  <i class="fa-solid fa-users"></i> </a> |
                            <a class="dropdown-item" asp-action="GetSubjects" asp-area="Manger" asp-route-id="@item.Id"> عرض مواد الفصل <i class="fa-solid fa-bookmark"></i> </a> |
                            <a class="dropdown-item" asp-action="GetTeachers" asp-area="Manger" asp-route-id="@item.Id"> عرض مدرسين الفصل <i class="fa-solid fa-chalkboard-user"></i> </a>


                        </div>
                    </div>
                </td>


                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>




            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
}